#!/bin/bash

sudo cp mine /usr/local/bin/
sudo mkdir /opt/Minecraft
sudo cp mine.png /opt/Minecraft/
mkdir ~/.local/share/applications
cp minecraft.desktop ~/.local/share/applications/
sudo cp minecraft.desktop /usr/share/applications/
